### ISSUE TITLE
With the release of jackson-jr record deserialisation should be available and therefore manual mapping should not be necessary

### ISSUE THREAD

**Issue by Giovds** [Giovds/outdated-maven-plugin#60]
The `QueryClient#toSearchResponse()` should not be manually mapping the values anymore and could use records instead.
The project uses jackson-jr 2.18 already. The issue is resolved here: https://github.com/FasterXML/jackson-jr/issues/162

**Comment by RomeoIndiaJulietUniform** [comment]
Hii @Giovds, I have solved this issue in my local, all the tests are passing. Can u pls assign me the task. Attaching Snapshot for better understanding :

## Changes 
![Screenshot from 2024-10-05 12-04-22](https://github.com/user-attachments/assets/bcf55773-a470-4eb1-b709-b4406909b7da)

## Tests
![Screenshot from 2024-10-05 12-03-37](https://github.com/user-attachments/assets/e8a574bb-47f1-4707-bbeb-0b9c4945c120)

**Comment by Giovds** [comment]
Resolved with #62
